"""Dataset manifest schema and loading utilities.

This module defines unified structures for dataset manifests, supporting both
CSV-based dataset index and JSON-based detailed file metadata.

The manifest system bridges dataset discovery (KnownDataset registry) with
training pipelines by providing upfront shape information, preprocessing status,
and file metadata.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any


@dataclass(frozen=True)
class FileMetadata:
    """Metadata for a single file in a dataset."""

    file_path: str
    """Absolute or relative path to the file."""

    shape: tuple[int, ...] | None = None
    """Tensor shape (channels, height, width) or (channels, depth, height, width)."""

    dtype: str | None = None
    """NumPy-style dtype string (e.g., 'float32', 'complex64')."""

    contrast: str | None = None
    """MRI contrast (e.g., 'T1w', 'T2w', 'FLAIR')."""

    preprocessing_status: str = "original"
    """Status: 'original', 'normalized', 'registered', 'transform', 'kspace'."""

    file_size_bytes: int | None = None
    """File size in bytes."""

    checksum: str | None = None
    """Optional hash for integrity validation."""

    metadata: dict[str, Any] = field(default_factory=dict)
    """Additional metadata (coil_sensitivity, b_value, etc.)."""


@dataclass(frozen=True)
class DatasetManifest:
    """Complete manifest for a dataset variant.

    Typically generated by scanning a dataset directory and collating
    file-level metadata.
    """

    dataset_key: str
    """Registry key for the dataset (e.g., 'fastmri_brain_multicoil')."""

    variant: str
    """Preprocessing variant (e.g., 'original', 'normalized', 'kspace')."""

    display_name: str
    """Human-readable name."""

    dataset_type: str
    """Type: 'kspace', '2d', '3d_volumetric', 'dicom_series', etc."""

    description: str = ""
    """Dataset description."""

    files: list[FileMetadata] = field(default_factory=list)
    """Metadata for all files in this variant."""

    scanned_at: float | None = None
    """Unix timestamp of when the manifest was generated."""

    canonical_shape: tuple[int, ...] | None = None
    """Expected/typical shape for this variant (used as validation target)."""

    total_files: int = 0
    """Total file count (cached for quick access)."""

    total_size_bytes: int = 0
    """Total data size across all files."""

    metadata: dict[str, Any] = field(default_factory=dict)
    """Additional metadata (contrasts present, coil counts, etc.)."""

    manifest_version: str = "1.0"
    """Schema version for migration tracking."""

    def get_shapes(self) -> list[tuple[int, ...]]:
        """Extract unique shapes from file metadata."""
        shapes = set()
        for file_meta in self.files:
            if file_meta.shape is not None:
                shapes.add(file_meta.shape)
        return sorted(list(shapes))

    def get_contrasts(self) -> set[str]:
        """Extract unique contrasts present in this manifest."""
        return {fm.contrast for fm in self.files if fm.contrast is not None}

    def get_file_count_by_contrast(self) -> dict[str, int]:
        """Count files per contrast."""
        counts: dict[str, int] = {}
        for file_meta in self.files:
            if file_meta.contrast:
                counts[file_meta.contrast] = counts.get(file_meta.contrast, 0) + 1
        return counts


@dataclass(frozen=True)
class DatasetManifestIndex:
    """Index of all dataset manifests (replaces old CSV structure).

    Provides O(1) lookup of dataset metadata and supports querying
    by dataset key, variant, or preprocessing status.
    """

    manifests: dict[tuple[str, str], DatasetManifest] = field(default_factory=dict)
    """Maps (dataset_key, variant) → manifest."""

    created_at: float = field(default_factory=lambda: datetime.now().timestamp())
    """Timestamp of index creation."""

    index_version: str = "1.0"
    """Schema version."""

    def get_manifest(
        self,
        dataset_key: str,
        variant: str = "original",
    ) -> DatasetManifest | None:
        """Get manifest for a specific dataset + variant."""
        return self.manifests.get((dataset_key, variant))

    def get_all_variants(self, dataset_key: str) -> list[DatasetManifest]:
        """Get all variants for a dataset."""
        return [m for (key, _), m in self.manifests.items() if key == dataset_key]

    def get_dataset_keys(self) -> set[str]:
        """Get all dataset keys in the index."""
        return {key for key, _ in self.manifests.keys()}


# CSV-based manifest for backward compatibility
@dataclass(frozen=True)
class DatasetManifestCSV:
    """Legacy CSV-based manifest index (backward compatibility).

    Keeps existing CSV format while supporting enhanced metadata.
    """

    dataset_key: str
    display_name: str
    dataset_type: str
    description: str
    total_files: int
    total_size_mb: int
    scanned_at: float
    dataset_dir: str
    variants_available: list[str] = field(default_factory=list)
    """List of preprocessing variants with detailed JSON metadata."""

    @classmethod
    def from_dict(cls, row: dict[str, Any]) -> DatasetManifestCSV:
        """Parse CSV row into manifest."""
        return cls(
            dataset_key=row["dataset_key"],
            display_name=row["display_name"],
            dataset_type=row["dataset_type"],
            description=row.get("description", ""),
            total_files=int(float(row.get("total_files", 0))),
            total_size_mb=int(float(row.get("total_size_mb", 0))),
            scanned_at=float(row.get("scanned_at", 0)),
            dataset_dir=row["dataset_dir"],
            variants_available=(
                row.get("variants_available", "").split(";")
                if row.get("variants_available")
                else []
            ),
        )

    def to_dict(self) -> dict[str, Any]:
        """Convert to CSV row dict."""
        return {
            "dataset_key": self.dataset_key,
            "display_name": self.display_name,
            "dataset_type": self.dataset_type,
            "description": self.description,
            "total_files": self.total_files,
            "total_size_mb": self.total_size_mb,
            "scanned_at": self.scanned_at,
            "dataset_dir": self.dataset_dir,
            "variants_available": ";".join(self.variants_available),
        }
