"""Differential test: ``NUFFTForwardModel`` vs direct ``torchkbnufft`` calls.

The framework's ``NUFFTForwardModel`` (in ``nufft_ops.py``) wraps
``torchkbnufft.KbNufft`` / ``KbNufftAdjoint``.  This test validates that the
wrapper does not introduce any numerical deviation beyond floating-point
rounding by comparing it to an independent direct call to the same underlying
operators.

We use a golden-angle radial trajectory generated by ``GoldenAngleTrajectory``
with a small image (32×32) to keep the test CPU-fast.

Markers
-------
- ``differential`` : cross-implementation comparison
- ``physics``      : physics-correctness test

Reference-library guard
-----------------------
``torchkbnufft`` is imported via ``pytest.importorskip`` so the module
collects (and skips gracefully) when the library is not installed.
"""

from __future__ import annotations

import pytest
import torch

# ---------------------------------------------------------------------------
# Guard: importorskip makes the test skip rather than error on import.
# ---------------------------------------------------------------------------
tkbn = pytest.importorskip("torchkbnufft")

from mriforge.infrastructure.physics.nufft_ops import (  # noqa: E402
    GoldenAngleTrajectory,
    NUFFTForwardModel,
)

# ---------------------------------------------------------------------------
# Test parameters
# ---------------------------------------------------------------------------
_IM_SIZE = (32, 32)
_NUM_SPOKES = 16
_SAMPLES_PER_SPOKE = 32
_N_POINTS = _NUM_SPOKES * _SAMPLES_PER_SPOKE

# Tolerances: torchkbnufft uses float32 internally; relative L2 is generous.
_ATOL = 1e-5
_RTOL = 1e-4


@pytest.fixture(scope="module")
def radial_trajectory() -> torch.Tensor:
    """Golden-angle radial trajectory [1, 2, N] in [-π, π]."""
    gen = GoldenAngleTrajectory(
        im_size=_IM_SIZE,
        num_spokes=_NUM_SPOKES,
        samples_per_spoke=_SAMPLES_PER_SPOKE,
    )
    # generate() returns [T, 2, N]; take single frame → [2, N]
    traj = gen.generate(num_frames=1)[0]
    return traj  # shape [2, N]


@pytest.fixture(scope="module")
def complex_phantom() -> torch.Tensor:
    """Small complex64 phantom image [1, 1, H, W]."""
    torch.manual_seed(42)
    real = torch.randn(1, 1, *_IM_SIZE)
    imag = torch.randn(1, 1, *_IM_SIZE)
    return torch.complex(real, imag).to(torch.complex64)


# ---------------------------------------------------------------------------
# Reference: direct torchkbnufft calls (no framework wrapper)
# ---------------------------------------------------------------------------

def _direct_tkbn_forward(
    image: torch.Tensor,
    traj: torch.Tensor,
    im_size: tuple[int, int] = _IM_SIZE,
    grid_size_factor: float = 2.0,
    numpoints: int = 6,
) -> torch.Tensor:
    """Direct torchkbnufft forward call — independent of NUFFTForwardModel."""
    grid_size = tuple(int(s * grid_size_factor) for s in im_size)
    nufft = tkbn.KbNufft(im_size=im_size, grid_size=grid_size, numpoints=numpoints)
    nufft.eval()
    # trajectory must be [B, 2, N] or [2, N]
    t = traj.unsqueeze(0).expand(image.shape[0], -1, -1)
    with torch.no_grad():
        return nufft(image, t)


def _direct_tkbn_adjoint(
    kdata: torch.Tensor,
    traj: torch.Tensor,
    im_size: tuple[int, int] = _IM_SIZE,
    grid_size_factor: float = 2.0,
    numpoints: int = 6,
) -> torch.Tensor:
    """Direct torchkbnufft adjoint call — independent of NUFFTForwardModel."""
    grid_size = tuple(int(s * grid_size_factor) for s in im_size)
    adj_nufft = tkbn.KbNufftAdjoint(
        im_size=im_size, grid_size=grid_size, numpoints=numpoints
    )
    adj_nufft.eval()
    t = traj.unsqueeze(0).expand(kdata.shape[0], -1, -1)
    with torch.no_grad():
        return adj_nufft(kdata, t)


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


@pytest.mark.differential
@pytest.mark.physics
def test_nufft_forward_matches_direct_tkbn(
    complex_phantom: torch.Tensor,
    radial_trajectory: torch.Tensor,
) -> None:
    """NUFFTForwardModel.forward_project == direct tkbn.KbNufft call."""
    model = NUFFTForwardModel(im_size=_IM_SIZE)
    model.eval()

    with torch.no_grad():
        k_wrapper = model.forward_project(complex_phantom, radial_trajectory)

    k_direct = _direct_tkbn_forward(complex_phantom, radial_trajectory)

    assert k_wrapper.shape == k_direct.shape, (
        f"Shape mismatch: wrapper={k_wrapper.shape}, direct={k_direct.shape}"
    )

    # Complex L2 relative error
    diff_norm = (k_wrapper - k_direct).abs().norm()
    ref_norm = k_direct.abs().norm() + 1e-12
    rel_err = (diff_norm / ref_norm).item()
    assert rel_err < _RTOL, (
        f"NUFFTForwardModel forward vs direct tkbn: rel_err={rel_err:.3e} "
        f"(threshold {_RTOL:.1e})"
    )


@pytest.mark.differential
@pytest.mark.physics
def test_nufft_adjoint_matches_direct_tkbn(
    complex_phantom: torch.Tensor,
    radial_trajectory: torch.Tensor,
) -> None:
    """NUFFTForwardModel.adjoint_project == direct tkbn.KbNufftAdjoint call."""
    model = NUFFTForwardModel(im_size=_IM_SIZE)
    model.eval()

    # Simulate k-space to get a realistic input for the adjoint
    with torch.no_grad():
        k = model.forward_project(complex_phantom, radial_trajectory)
        x_wrapper = model.adjoint_project(k, radial_trajectory)

    x_direct = _direct_tkbn_adjoint(k, radial_trajectory)

    assert x_wrapper.shape == x_direct.shape, (
        f"Shape mismatch: wrapper={x_wrapper.shape}, direct={x_direct.shape}"
    )

    diff_norm = (x_wrapper - x_direct).abs().norm()
    ref_norm = x_direct.abs().norm() + 1e-12
    rel_err = (diff_norm / ref_norm).item()
    assert rel_err < _RTOL, (
        f"NUFFTForwardModel adjoint vs direct tkbn: rel_err={rel_err:.3e} "
        f"(threshold {_RTOL:.1e})"
    )


@pytest.mark.differential
@pytest.mark.physics
def test_nufft_adjoint_dot_product_identity(
    complex_phantom: torch.Tensor,
    radial_trajectory: torch.Tensor,
) -> None:
    """Dot-product test: <Ax, y> == <x, A^H y> for the NUFFT forward model.

    Uses the framework wrapper directly.  The test is agnostic to the
    internal torchkbnufft implementation — it only verifies that
    NUFFTForwardModel implements a true adjoint pair.
    """
    model = NUFFTForwardModel(im_size=_IM_SIZE)
    model.eval()

    torch.manual_seed(0)
    x = torch.complex(
        torch.randn(1, 1, *_IM_SIZE), torch.randn(1, 1, *_IM_SIZE)
    ).to(torch.complex64)
    y = torch.complex(
        torch.randn(1, 1, _N_POINTS), torch.randn(1, 1, _N_POINTS)
    ).to(torch.complex64)

    with torch.no_grad():
        Ax = model.forward_project(x, radial_trajectory)   # [1, 1, N]
        AHy = model.adjoint_project(y, radial_trajectory)  # [1, 1, H, W]

    # Adjoint identity <Ax, y> = <x, A^H y> with the convention <a,b>=sum(conj(a)·b).
    # Note rhs must be conj(x)·AHy, NOT conj(AHy)·x — the latter computes
    # conj(<x, A^H y>), which flips the sign of the imaginary part and spuriously
    # fails the test even for a correct adjoint.
    lhs = (Ax.conj() * y).sum()
    rhs = (x.conj() * AHy).sum()

    rel_err = ((lhs - rhs).abs() / (rhs.abs() + 1e-12)).item()
    assert rel_err < 1e-3, (
        f"Adjoint dot-product test failed: <Ax,y>={lhs.item():.6f}, "
        f"<x,A^Hy>={rhs.item():.6f}, rel_err={rel_err:.3e}"
    )


@pytest.mark.differential
@pytest.mark.physics
def test_nufft_output_is_complex64(
    complex_phantom: torch.Tensor,
    radial_trajectory: torch.Tensor,
) -> None:
    """NUFFTForwardModel always outputs complex64."""
    model = NUFFTForwardModel(im_size=_IM_SIZE)
    model.eval()
    with torch.no_grad():
        k = model.forward_project(complex_phantom, radial_trajectory)
    assert k.is_complex(), "NUFFT output must be complex"
