r"""TikZ / pgfplots export for the reporting pipeline.

Emits LaTeX-native versions of the key data-driven figures so papers under
``~/Work/research/papers`` and ``~/Work/research/writing`` can typeset them
as first-class TikZ rather than rasterised PDFs.

Two files per figure:

* ``<stem>.tikz`` — the bare ``tikzpicture`` (``\input`` it inside a paper).
* ``<stem>.tex``  — a ``standalone`` wrapper compilable directly with
  ``tectonic -X compile <stem>.tex``.

Deliberately **not** matplotlib's PGF backend: that backend shells out to a
live ``latex`` process for text metrics, which is fragile on hosts without a
TeX daemon. These emitters are pure string generation — writing ``.tex``
never requires LaTeX; only *rendering* does.

Colours reuse the house Okabe–Ito method mapping (``style.colour_for``) via
per-method ``\definecolor`` so a method keeps its colour across matplotlib
and TikZ outputs alike.
"""

from __future__ import annotations

import logging
from pathlib import Path

import pandas as pd

from .style import colour_for, pretty_label

logger = logging.getLogger(__name__)

_STANDALONE_HEADER = (
    "% Auto-generated by spectramr.infrastructure.reporting.tikz_export - do not edit.\n"
    "% Compile: tectonic -X compile {stem}.tex\n"
    "\\documentclass[tikz]{{standalone}}\n"
    "\\usepackage{{pgfplots}}\n"
    "\\pgfplotsset{{compat=1.18}}\n"
    "\\begin{{document}}\n"
)
_STANDALONE_FOOTER = "\\end{document}\n"

_AXIS_STYLE = (
    "width=88mm, height=60mm,\n"
    "  tick label style={font=\\scriptsize},\n"
    "  label style={font=\\small},\n"
    "  legend style={font=\\scriptsize, draw=none, fill=none},\n"
    "  legend cell align=left,\n"
    "  axis lines=left"
)


_TEX_ESCAPES = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def _tex_escape(text: str) -> str:
    """Escape the LaTeX specials that plausibly appear in metric/method names.

    Single character-wise pass — sequential ``str.replace`` would re-escape
    the braces introduced by earlier replacements.
    """
    return "".join(_TEX_ESCAPES.get(ch, ch) for ch in str(text))


def _coords(series: pd.Series) -> str:
    """Format a step-indexed series as pgfplots ``coordinates``."""
    pairs = [
        f"({x:.10g},{y:.10g})"
        for x, y in series.items()
        if pd.notna(y) and abs(float(y)) != float("inf")
    ]
    return " ".join(pairs)


def _colour_defs(methods: list[str]) -> tuple[str, dict[str, str]]:
    """Return ``\\definecolor`` lines + a method → colour-name mapping."""
    lines: list[str] = []
    names: dict[str, str] = {}
    for i, method in enumerate(methods):
        name = f"spectramr{chr(ord('A') + (i % 26))}{i // 26 if i >= 26 else ''}"
        hexval = colour_for(str(method), fallback_index=i).lstrip("#").upper()
        lines.append(f"\\definecolor{{{name}}}{{HTML}}{{{hexval}}}")
        names[str(method)] = name
    return "\n".join(lines), names


def _write_pair(out_dir: Path, stem: str, tikzpicture: str) -> Path:
    """Write ``<stem>.tikz`` + the standalone ``<stem>.tex``; return the .tex path."""
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / f"{stem}.tikz").write_text(tikzpicture)
    tex = _STANDALONE_HEADER.format(stem=stem) + tikzpicture + _STANDALONE_FOOTER
    tex_path = out_dir / f"{stem}.tex"
    tex_path.write_text(tex)
    return tex_path


def curve_to_tikz(
    df: pd.DataFrame,
    out_dir: str | Path,
    *,
    metric: str,
    split: str | None = None,
    ymode: str = "linear",
) -> Path | None:
    """Emit one metric-vs-step pgfplots figure (one line per method).

    Returns the standalone ``.tex`` path, or ``None`` when the frame holds no
    positive-step rows for ``metric`` (total on bad input, like the plotters).

    Raises:
        ValueError: on an unknown ``ymode`` (no silent fallback).
    """
    if ymode not in ("linear", "log"):
        raise ValueError(f"unknown ymode {ymode!r}; choose from ['linear', 'log']")
    if df.empty or "metric" not in df.columns:
        return None
    sub = df[df["metric"] == metric]
    if split is not None and "split" in sub.columns:
        sub = sub[sub["split"] == split]
    sub = sub[sub["step"].fillna(-1) >= 0].dropna(subset=["value"])
    if sub.empty:
        return None

    methods = [str(m) for m in sub["method"].unique()]
    colour_block, colour_names = _colour_defs(methods)
    plots: list[str] = []
    for method in methods:
        series = sub[sub["method"] == method].groupby("step")["value"].mean().sort_index()
        coords = _coords(series)
        if not coords:
            continue
        plots.append(
            f"\\addplot[{colour_names[method]}, thick] coordinates {{ {coords} }};\n"
            f"\\addlegendentry{{{_tex_escape(method)}}}"
        )
    if not plots:
        return None
    ylabel = _tex_escape(pretty_label(metric))
    log_opt = "ymode=log,\n  " if ymode == "log" else ""
    tikzpicture = (
        "\\begin{tikzpicture}\n"
        f"{colour_block}\n"
        f"\\begin{{axis}}[\n  {log_opt}{_AXIS_STYLE},\n"
        f"  xlabel={{{_tex_escape(pretty_label('step'))}}},\n"
        f"  ylabel={{{ylabel}}},\n"
        "  legend pos=north east]\n" + "\n".join(plots) + "\n"
        "\\end{axis}\n"
        "\\end{tikzpicture}\n"
    )
    stem = f"curve_{metric}" + (f"_{split}" if split else "")
    return _write_pair(Path(out_dir), stem, tikzpicture)


def pareto_to_tikz(
    df: pd.DataFrame, out_dir: str | Path, *, metric: str = "psnr", cost: str = "params_m"
) -> Path | None:
    """Emit the headline metric-vs-cost scatter with per-method labels."""
    if df.empty or "metric" not in df.columns:
        return None
    present = set(df["metric"].unique())
    if metric not in present or cost not in present:
        return None
    pivot = (
        df[df["metric"].isin({metric, cost})]
        .pivot_table(index="method", columns="metric", values="value", aggfunc="last")
        .dropna(subset=[metric, cost])
    )
    if pivot.empty:
        return None

    methods = [str(m) for m in pivot.index]
    colour_block, colour_names = _colour_defs(methods)
    plots: list[str] = []
    for method in methods:
        x = float(pivot.loc[method, cost])
        y = float(pivot.loc[method, metric])
        plots.append(
            f"\\addplot[{colour_names[method]}, only marks, mark=*] "
            f"coordinates {{ ({x:.10g},{y:.10g}) }} "
            f"node[pin={{45:{_tex_escape(method)}}}] {{}};"
        )
    tikzpicture = (
        "\\begin{tikzpicture}\n"
        f"{colour_block}\n"
        f"\\begin{{axis}}[\n  {_AXIS_STYLE},\n"
        f"  xlabel={{{_tex_escape(pretty_label(cost))}}},\n"
        f"  ylabel={{{_tex_escape(pretty_label(metric))}}}]\n" + "\n".join(plots) + "\n"
        "\\end{axis}\n"
        "\\end{tikzpicture}\n"
    )
    return _write_pair(Path(out_dir), f"pareto_{metric}_vs_{cost}", tikzpicture)


def export_tikz_figures(
    df: pd.DataFrame, out_dir: str | Path, *, max_curves: int = 4
) -> dict[str, Path]:
    """Emit the standard TikZ bundle for one report; return ``{id: tex_path}``.

    Selection mirrors the matplotlib presets: loss-like training curves
    (log-y), headline validation metrics (linear), and the params-vs-PSNR
    Pareto when the run-summary rows provide a cost axis. Per-figure failures
    log and continue (report-time soft-fail, same contract as the plotters).
    """
    out_dir = Path(out_dir)
    written: dict[str, Path] = {}
    if df.empty or "metric" not in df.columns:
        return written

    all_metrics = [str(m) for m in df["metric"].unique()]
    loss_like = [m for m in all_metrics if "loss" in m.lower()][:max_curves]
    headline = [m for m in ("val_psnr", "val_ssim", "psnr", "ssim") if m in all_metrics][
        :max_curves
    ]
    jobs: list[tuple[str, dict]] = []
    for m in loss_like:
        # no split pin — metric names already encode the split by prefix
        # convention (val_loss vs loss); log-y only when strictly positive
        # (a log axis over ≤0 samples fails at *compile* time, not here).
        vals = df[df["metric"] == m]["value"].dropna()
        ymode = "log" if len(vals) and (vals > 0).all() else "linear"
        jobs.append((f"tikz_curve_{m}", {"metric": m, "ymode": ymode}))
    for m in headline:
        jobs.append((f"tikz_curve_{m}", {"metric": m}))
    for fig_id, kwargs in jobs:
        try:
            path = curve_to_tikz(df, out_dir, **kwargs)
        except Exception as exc:  # report-time soft-fail
            logger.warning("tikz export '%s' failed: %s", fig_id, exc)
            continue
        if path is not None:
            written[fig_id] = path
    for metric in ("psnr", "ssim"):
        try:
            path = pareto_to_tikz(df, out_dir, metric=metric)
        except Exception as exc:  # report-time soft-fail
            logger.warning("tikz pareto '%s' failed: %s", metric, exc)
            continue
        if path is not None:
            written[f"tikz_pareto_{metric}"] = path
            break  # one headline Pareto is enough
    return written
