"""Multi-Physics Bloch Layer for MRI Signal Synthesis.

This module implements a differentiable layer that synthesizes MRI signals
from tissue parameters (ρ, T1, T2) using physically accurate equations
for different pulse sequences:

1. **Spin Echo (SE)** - for T2-weighted imaging
2. **Inversion Recovery (IR)** - for FLAIR, ULF T1-weighted (TI=340ms)
3. **Gradient Echo (GRE/SPGR)** - for HF T1-weighted (3T MPRAGE)

References:
- Sarracanie & Salameh (2020): "Low-field MRI: hardware and physics"
- Bernstein et al.: "Principles of Magnetic Resonance Imaging"

Author: Generated by AI Agent
Date: 2026-01-29
"""

import math
from typing import Any

import torch
import torch.nn as nn


class MultiPhysicsBlochLayer(nn.Module):
    """Differentiable MRI signal synthesis from tissue parameters.

    Supports multiple pulse sequence types with physically accurate equations.
    All internal computations use seconds for numerical stability.

    Attributes:
        flip_angle: Learnable flip angle for GRE sequences (radians)
        eps: Numerical stability epsilon
    Mathematical Formulation:
    .. math::

        \\mathcal{O}_{Bloch}(T_1, T_2, PD) = \text{Signal}_{\text{Seq}}"""

    # Sequence type enum values
    SEQ_SPIN_ECHO = 0  # T2w
    SEQ_INVERSION_RECOVERY = 1  # FLAIR, ULF T1w
    SEQ_GRADIENT_ECHO = 2  # HF T1w (MPRAGE/SPGR)
    SEQ_DIFFUSION_WEIGHTED = 3  # DWI

    def __init__(
        self,
        default_flip_angle_deg: float = 10.0,
        learnable_flip_angle: bool = True,
        eps: float = 1e-6,
    ):
        """Initialize the Multi-Physics Bloch Layer.

        Args:
            default_flip_angle_deg: Default flip angle in degrees for GRE
            learnable_flip_angle: If True, flip angle is a learnable parameter
            eps: Numerical stability epsilon for divisions
        """
        super().__init__()

        self.eps = eps

        # Flip angle for GRE sequences
        flip_rad = default_flip_angle_deg * math.pi / 180.0
        if learnable_flip_angle:
            self.flip_angle = nn.Parameter(torch.tensor(flip_rad))
        else:
            self.register_buffer("flip_angle", torch.tensor(flip_rad))

    def forward(
        self,
        tissue_params: dict[str, torch.Tensor],
        metadata: dict[str, Any],
    ) -> torch.Tensor:
        """Synthesize MRI signal from tissue parameters.

        Args:
            tissue_params: Dict with keys 'rho', 't1', 't2' (all in ms).
                - rho: Proton density [B, 1, H, W] in [0, 1]
                - t1: T1 relaxation [B, 1, H, W] in ms
                - t2: T2 relaxation [B, 1, H, W] in ms
                - t2star: T2* relaxation [B, 1, H, W] in ms (optional)
                - adc: Apparent Diffusion Coefficient [B, 1, H, W] (optional)
                - susceptibility_phase: χ-induced phase [B, 1, H, W] (optional)
                - bias_field: Multiplicative bias field [B, 1, H, W] (optional)
            metadata: Dict with sequence parameters:
                - TR: Repetition time (ms or tensor)
                - TE: Echo time (ms or tensor)
                - TI: Inversion time (ms or tensor, optional)
                - b_value: Diffusion weighting (s/mm², optional)
                - contrast_type: int or str indicating sequence type

        Returns:
            Synthesized signal [B, 1, H, W] in [0, 1] range

        forward method for MultiPhysicsBlochLayer.

        Executes PyTorch tensor operations.

        Args:
            tissue_params (torch.Tensor, shape (B, C, H, W) or (B, C, D, H, W)): Expected input tensor.
            metadata (dict[str, Any]): Expected input tensor.

        Returns:
            torch.Tensor: Output tensor.

        Hardware/Device Context:
            Supports Mixed Precision (AMP) and CUDA streams if configured in DataStagingService."""
        # Extract tissue parameters
        rho = tissue_params["rho"]  # [0, 1]
        t1_ms = tissue_params["t1"]  # ms
        t2_ms = tissue_params["t2"]  # ms

        device = rho.device
        batch_size = rho.shape[0]

        # Convert tissue params to seconds for numerical stability
        # [FIX] Safety Clamping: Prevent division by zero in exponentials
        t1_clamped = torch.clamp(t1_ms, min=10.0)
        t2_clamped = torch.clamp(t2_ms, min=1.0)

        t1 = t1_clamped / 1000.0  # ms -> s
        t2 = t2_clamped / 1000.0  # ms -> s

        if "t2star" in tissue_params:
            t2star_ms = tissue_params["t2star"]
            t2star_clamped = torch.clamp(t2star_ms, min=1.0)
            t2star = t2star_clamped / 1000.0  # ms -> s
        else:
            t2star = t2

        # Optional susceptibility phase for GRE
        susc_phase = tissue_params.get("susceptibility_phase")

        # Extract sequence parameters (convert to seconds)
        tr = self._get_param(metadata, "TR", default=2.0, device=device) / 1000.0
        te = self._get_param(metadata, "TE", default=0.01, device=device) / 1000.0
        ti = self._get_param(metadata, "TI", default=0.0, device=device) / 1000.0
        b_value = self._get_param(metadata, "b_value", default=0.0, device=device)

        # Determine sequence type
        seq_type = self._get_sequence_type(metadata, ti, te, device)

        # Expand sequence params to spatial dimensions [B, 1, 1, 1]
        tr = self._expand_param(tr, batch_size, device)
        te = self._expand_param(te, batch_size, device)
        ti = self._expand_param(ti, batch_size, device)
        b_value = self._expand_param(b_value, batch_size, device)
        seq_type = self._expand_param(seq_type, batch_size, device, dtype=torch.long)

        # [Phase 5] Allow dynamic alpha prediction from metadata
        alpha_tensor = None
        if "alpha" in metadata:
            alpha_val = metadata["alpha"]
            if isinstance(alpha_val, torch.Tensor):
                alpha_tensor = alpha_val.to(device)
            else:
                alpha_tensor = torch.tensor([alpha_val], device=device, dtype=torch.float32)
            alpha_tensor = self._expand_param(alpha_tensor, batch_size, device)

        # Compute signal for each sequence type
        se_signal = self._synthesize_spin_echo(rho, t1, t2, tr, te)
        ir_signal = self._synthesize_inversion_recovery(rho, t1, t2, tr, te, ti)
        gre_signal = self._synthesize_gradient_echo(
            rho, t1, t2star, tr, te, susc_phase, alpha=alpha_tensor
        )

        # DWI signal
        adc = tissue_params.get("adc")
        dwi_signal = self._synthesize_diffusion_weighted(rho, t1, t2, tr, te, b_value, adc)

        # Select signal based on sequence type (differentiable via torch.where)
        signal = torch.zeros_like(rho)
        signal = torch.where(seq_type == self.SEQ_SPIN_ECHO, se_signal, signal)
        signal = torch.where(seq_type == self.SEQ_INVERSION_RECOVERY, ir_signal, signal)
        signal = torch.where(seq_type == self.SEQ_GRADIENT_ECHO, gre_signal, signal)
        signal = torch.where(seq_type == self.SEQ_DIFFUSION_WEIGHTED, dwi_signal, signal)

        # Apply bias field if present
        if "bias_field" in tissue_params:
            signal = signal * tissue_params["bias_field"]

        # Normalize to [0, 1] range per batch (prevents scale explosion)
        signal = self._normalize_signal(signal)

        return signal

    def _synthesize_spin_echo(
        self,
        rho: torch.Tensor,
        t1: torch.Tensor,
        t2: torch.Tensor,
        tr: torch.Tensor,
        te: torch.Tensor,
    ) -> torch.Tensor:
        """Spin Echo (SE) signal equation for T2-weighted imaging.

        S = ρ × (1 - exp(-TR/T1)) × exp(-TE/T2)
        """
        e1 = torch.exp(-tr / (t1 + self.eps))
        e2 = torch.exp(-te / (t2 + self.eps))
        signal = rho * (1 - e1) * e2
        return signal.clamp(0, 1)

    def _synthesize_inversion_recovery(
        self,
        rho: torch.Tensor,
        t1: torch.Tensor,
        t2: torch.Tensor,
        tr: torch.Tensor,
        te: torch.Tensor,
        ti: torch.Tensor,
    ) -> torch.Tensor:
        """Inversion Recovery (IR) signal equation for FLAIR/ULF T1w.

        S = ρ × |1 - 2×exp(-TI/T1) + exp(-TR/T1)| × exp(-TE/T2)

        Note: Using abs() because magnitude images discard phase.
        """
        e_ti = torch.exp(-ti / (t1 + self.eps))
        e_tr = torch.exp(-tr / (t1 + self.eps))
        e2 = torch.exp(-te / (t2 + self.eps))

        # IR signal equation with magnitude (abs for phase-insensitive)
        ir_term = torch.abs(1 - 2 * e_ti + e_tr)
        signal = rho * ir_term * e2

        return signal.clamp(0, 1)

    def _synthesize_gradient_echo(
        self,
        rho: torch.Tensor,
        t1: torch.Tensor,
        t2star: torch.Tensor,
        tr: torch.Tensor,
        te: torch.Tensor,
        susceptibility_phase: torch.Tensor = None,
        alpha: torch.Tensor = None,
    ) -> torch.Tensor:
        """Gradient Echo (GRE/SPGR) signal equation for HF T1w.

        S = ρ × [sin(α)(1-E1)] / [1 - cos(α)E1] × E2* × coherence_loss(χ)
        where E1 = exp(-TR/T1), E2* = exp(-TE/T2*), and

            coherence_loss(χ) = exp(-φ² / 2)

        is the Gaussian intravoxel static-dephasing envelope. ``φ`` =
        ``susceptibility_phase`` is the χ-induced phase DISPERSION across the
        voxel (radians) at this TE, so the loss is a *dimensionless* function
        of φ alone — TE-dependence is carried by φ (phase accrues over TE),
        not by an explicit extra TE factor.
        """
        e1 = torch.exp(-tr / (t1 + self.eps))
        e2star = torch.exp(-te / (t2star + self.eps))  # Using T2*

        if alpha is None:
            alpha = torch.abs(self.flip_angle) + 1e-6
        else:
            alpha = torch.abs(alpha) + 1e-6
            if alpha.ndim < rho.ndim:
                for _ in range(rho.ndim - alpha.ndim):
                    alpha = alpha.unsqueeze(-1)
            alpha = alpha.expand_as(rho)

        sin_a = torch.sin(alpha)
        cos_a = torch.cos(alpha)

        denom = 1 - cos_a * e1

        is_small_denom = torch.abs(denom) < 1e-4
        denom_safe = torch.where(is_small_denom, torch.ones_like(denom), denom)

        gre_signal = (sin_a * (1 - e1)) / (denom_safe + 1e-8) * e2star
        gre_approx = alpha * (tr / (t1 + self.eps)) * e2star

        signal = torch.where(is_small_denom, gre_approx, gre_signal)
        signal = rho * signal

        if susceptibility_phase is not None:
            # Gaussian static-dephasing envelope: a dimensionless function of
            # the (dimensionless) intravoxel phase dispersion φ. The previous
            # form exp(-|φ|·TE) multiplied a phase by a time — dimensionally
            # invalid, and double-counted TE since φ already accrues over TE.
            coherence_loss = torch.exp(-0.5 * susceptibility_phase**2)
            signal = signal * coherence_loss

        return signal.clamp(0, 1)

    def _synthesize_diffusion_weighted(
        self,
        rho: torch.Tensor,
        t1: torch.Tensor,
        t2: torch.Tensor,
        tr: torch.Tensor,
        te: torch.Tensor,
        b_value: torch.Tensor,
        adc: torch.Tensor | None = None,
    ) -> torch.Tensor:
        """Diffusion-Weighted Imaging (DWI) signal equation.

        S = ρ·(1 - exp(-TR/T1))·exp(-TE/T2)·exp(-b·ADC)
        """
        # T1 and T2 relaxation (Spin Echo base)
        e1 = torch.exp(-tr / (t1 + self.eps))
        e2 = torch.exp(-te / (t2 + self.eps))

        # Default ADC if not provided (typical brain values ≈ 0.8e-3 mm²/s)
        if adc is None:
            adc = torch.full_like(rho, 0.8e-3)

        # Diffusion weighting
        e_diff = torch.exp(-b_value * adc)

        signal = rho * (1 - e1) * e2 * e_diff
        return signal.clamp(0, 1)

    def _get_param(
        self,
        metadata: dict,
        key: str,
        default: float,
        device: torch.device,
    ) -> torch.Tensor:
        """Extract parameter from metadata, handling various formats."""
        value = metadata.get(key, default)

        if isinstance(value, torch.Tensor):
            return value.to(device)
        elif isinstance(value, (int, float)):
            return torch.tensor(value, dtype=torch.float32, device=device)
        else:
            return torch.tensor(default, dtype=torch.float32, device=device)

    def _expand_param(
        self,
        param: torch.Tensor,
        batch_size: int,
        device: torch.device,
        dtype: torch.dtype = torch.float32,
    ) -> torch.Tensor:
        """Expand scalar/1D param to [B, 1, 1, 1] for broadcasting."""
        if param.dim() == 0:
            # Scalar -> [B, 1, 1, 1]
            return param.view(1, 1, 1, 1).expand(batch_size, 1, 1, 1).to(dtype)
        elif param.dim() == 1:
            # [B] -> [B, 1, 1, 1]
            return param.view(-1, 1, 1, 1).to(dtype)
        else:
            return param.to(dtype)

    def _get_sequence_type(
        self,
        metadata: dict,
        ti: torch.Tensor,
        te: torch.Tensor,
        device: torch.device,
    ) -> torch.Tensor:
        """Determine sequence type from metadata or infer from parameters."""
        # Check for explicit contrast_type
        contrast_type = metadata.get("contrast_type")

        if contrast_type is not None:
            if isinstance(contrast_type, int):
                return torch.tensor(contrast_type, device=device)
            elif isinstance(contrast_type, str):
                # Map string to enum
                contrast_lower = contrast_type.lower()
                if "flair" in contrast_lower or "ir" in contrast_lower:
                    return torch.tensor(self.SEQ_INVERSION_RECOVERY, device=device)
                elif "t2" in contrast_lower or "se" in contrast_lower:
                    return torch.tensor(self.SEQ_SPIN_ECHO, device=device)
                elif (
                    "t1" in contrast_lower or "gre" in contrast_lower or "mprage" in contrast_lower
                ):
                    return torch.tensor(self.SEQ_GRADIENT_ECHO, device=device)
            elif isinstance(contrast_type, torch.Tensor):
                return contrast_type.to(device)

        # Infer from TI and TE values
        ti_val = ti.max().item() if isinstance(ti, torch.Tensor) else ti
        te_val = te.max().item() if isinstance(te, torch.Tensor) else te

        if ti_val > 0.1:  # TI > 100ms indicates IR sequence
            return torch.tensor(self.SEQ_INVERSION_RECOVERY, device=device)
        elif te_val > 0.05:  # TE > 50ms indicates T2w (SE)
            return torch.tensor(self.SEQ_SPIN_ECHO, device=device)
        else:
            return torch.tensor(self.SEQ_GRADIENT_ECHO, device=device)

    def _normalize_signal(self, signal: torch.Tensor) -> torch.Tensor:
        """Normalize signal to [0, 1] using detached statistics.

        # Target images are [0, 1]. To match ranges without gradient explosion:
        # 1. Compute min/max for scaling.
        # 2. DETACH the stats so we don't backprop through the normalization scaling.
        #    This treats the scaling as a constant "Receiver Gain".
        # 3. Use clamp on the denominator to avoid multiplying incoming gradients
        #    by huge values (e.g. 1e6 when dynamic range is 1e-6)
        """
        # Compute stats per batch item
        flat = signal.view(signal.size(0), -1)
        vmin = flat.amin(dim=1, keepdim=True).view(-1, 1, 1, 1).detach()
        vmax = flat.amax(dim=1, keepdim=True).view(-1, 1, 1, 1).detach()

        # Avoid normalization for near-zero or constant signals
        # If signal is uniform, (vmax - vmin) is 0.
        is_uniform = (vmax - vmin) < self.eps

        # Scale down uniform signals to avoid exploding gradients
        # Use a safe denominator clamped to at least 0.01 (~100x max amplification)
        safe_denom = torch.clamp(vmax - vmin, min=0.01)
        normalized = (signal - vmin) / safe_denom

        # Return original signal (clamped) for uniform cases to preserve quantitative tests
        return torch.where(is_uniform, signal.clamp(0, 1), normalized)


# Convenience function for quick synthesis
def synthesize_mri_signal(
    tissue_params: dict[str, torch.Tensor],
    metadata: dict[str, Any],
) -> torch.Tensor:
    """Synthesize MRI signal using Multi-Physics Bloch equations.

    Args:
        tissue_params: Dict with 'rho', 't1', 't2' tensors
        metadata: Dict with 'TR', 'TE', 'TI', 'contrast_type'

    Returns:
        Synthesized signal tensor
    """
    layer = MultiPhysicsBlochLayer()
    return layer(tissue_params, metadata)
