r"""Primary-decomposition-inspired vanishing-ideal residual for tissue maps.

Primary decomposition (Lasker--Noether) writes an algebraic variety as a
finite union of irreducible components, :math:`V(I)=\bigcup_k V(Q_k)` for
primary ideals :math:`Q_k`. The *vanishing ideal* of a union of varieties
is generated by the **product** of the component generators: a point
:math:`\theta` lies on :math:`\bigcup_k V(g_k)` iff

.. math::

    \prod_k g_k(\theta) = 0 .

This module exposes a differentiable surrogate of that membership test for
quantitative MRI: each tissue class :math:`k` is modelled as a quadratic
component variety

.. math::

    g_k(\theta) = (\theta-c_k)^\top A_k (\theta-c_k) - r_k^2 ,

an ellipsoidal shell around a class centre :math:`c_k` in parameter space
:math:`\theta=(M_0,T_1,T_2)`. The vanishing-ideal residual
:math:`|\prod_k g_k(\theta)|` is zero exactly when a voxel sits on one of
the component varieties and grows as it leaves the union.

This is an honest *surrogate* — it captures the union-of-varieties algebra
of primary decomposition (product of generators), not a full Gröbner-basis
decomposition, which is non-differentiable and out of scope for a training
penalty. Named so the ``primary_ideal`` strategy is no longer a façade.
"""

from __future__ import annotations

import torch


def quadratic_component(
    theta: torch.Tensor,
    center: torch.Tensor,
    radius: float,
    metric: torch.Tensor | None = None,
) -> torch.Tensor:
    r"""Evaluate one quadratic component generator ``g_k(theta)``.

    Args:
        theta: Points ``[..., d]`` in parameter space.
        center: Component centre ``c_k`` of shape ``[d]``.
        radius: Shell radius ``r_k`` (the variety is the ``g_k=0`` shell).
        metric: Optional SPD matrix ``A_k`` ``[d, d]`` (defaults to identity).

    Returns:
        ``g_k(theta)`` with shape ``theta.shape[:-1]``.
    """
    diff = theta - center
    if metric is None:
        quad = (diff * diff).sum(dim=-1)
    else:
        quad = torch.einsum("...i,ij,...j->...", diff, metric, diff)
    return quad - radius**2


def vanishing_ideal_residual(
    theta: torch.Tensor,
    centers: torch.Tensor,
    radii: torch.Tensor,
    *,
    log_domain: bool = True,
) -> torch.Tensor:
    r"""Residual ``|prod_k g_k(theta)|`` for the union of component varieties.

    Args:
        theta: Parameter-space points ``[..., d]``.
        centers: Component centres ``[K, d]``.
        radii: Component radii ``[K]``.
        log_domain: If True (default), accumulate the product in log-space
            (``exp(sum log|g_k|)``) for numerical stability when ``K`` is
            large, preserving the same minimiser (the product is zero iff any
            factor is zero).

    Returns:
        Non-negative residual with shape ``theta.shape[:-1]``.
    """
    if centers.shape[0] != radii.shape[0]:
        raise ValueError(f"centers/radii count mismatch: {centers.shape[0]} vs {radii.shape[0]}")
    factors = []
    for k in range(centers.shape[0]):
        g_k = quadratic_component(theta, centers[k], float(radii[k].item()))
        factors.append(g_k.abs())
    stacked = torch.stack(factors, dim=0)  # [K, ...]
    if log_domain:
        # |prod_k g_k| = exp(sum_k log|g_k|); guard zeros with a small eps.
        eps = 1e-12
        return torch.exp(torch.log(stacked + eps).sum(dim=0))
    out = stacked[0]
    for k in range(1, stacked.shape[0]):
        out = out * stacked[k]
    return out


__all__ = ["quadratic_component", "vanishing_ideal_residual"]
