import torch
import torch.nn as nn
import torch.nn.functional as F

from mriforge.models.interfaces.models import IGenerator
from mriforge.models.registry import register_model


class MainNetwork(nn.Module):
    """Target network whose weights are generated by the Hypernetwork."""

    def __init__(self, in_channels, out_channels):
        """__init__.

        Args:
            in_channels (Any): Description.
            out_channels (Any): Description.
        """
        super().__init__()
        # Simple 2-layer CNN
        # We will manually apply weights generated by Hypernetwork
        pass

    def forward(self, x, weights):
        # weights is a dictionary of tensors
        """forward.

        Args:
            x (Any): Description.
            weights (Any): Description.
        Returns:
            Any: Description.

        forward method for MainNetwork.

        Executes PyTorch tensor operations.

        Args:
            x (torch.Tensor, shape (B, C, H, W) [inferred]): Expected input tensor.
            weights (torch.Tensor, shape (B, C, H, W) [inferred]): Expected input tensor.

        Returns:
            torch.Tensor: Output tensor with shape matching the operation.

        Hardware/Device Context:
            Supports Mixed Precision (AMP) and CUDA streams if configured in DataStagingService."""
        x = F.conv2d(x, weights["conv1.weight"], bias=weights["conv1.bias"], padding=1)
        x = F.relu(x)
        x = F.conv2d(x, weights["conv2.weight"], bias=weights["conv2.bias"], padding=1)
        return x


import torch.nn as nn

__all__ = ["HypernetworkGenerator"]


@register_model(name="hypernetwork", training_mode="reconstruction")
class HypernetworkGenerator(nn.Module, IGenerator):
    """
    Hypernetwork for personalized MRI reconstruction (Experiment 115).

    Generates the weights of a 'Main' reconstruction network based on an input embedding
    (e.g., patient ID, scanner type, or style code).
    """

    def __init__(
        self,
        in_channels: int = 1,
        out_channels: int = 1,
        hypernet_embedding_dim: int = 32,
        hidden_dim: int = 64,
        _main_net_features: int = 32,
    ):
        """__init__.

        Args:
            in_channels (int): Description.
            out_channels (int): Description.
            hypernet_embedding_dim (int): Description.
            hidden_dim (int): Description.
            _main_net_features (int): Description.
        """
        super().__init__()
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.embedding_dim = hypernet_embedding_dim

        # Hypernetwork: Embedding -> Weights
        # Target architecture:
        # Conv1: 1 -> 16 (3x3) = 1*16*3*3 + 16 = 144 + 16 = 160 params
        # Conv2: 16 -> 1 (3x3) = 16*1*3*3 + 1 = 144 + 1 = 145 params
        # Total params to generate: 305

        self.target_hidden = 16

        self.hyper_net = nn.Sequential(
            nn.Linear(self.embedding_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
        )

        # Heads for each weight tensor
        self.w1_head = nn.Linear(hidden_dim, in_channels * self.target_hidden * 3 * 3)
        self.b1_head = nn.Linear(hidden_dim, self.target_hidden)

        self.w2_head = nn.Linear(hidden_dim, self.target_hidden * out_channels * 3 * 3)
        self.b2_head = nn.Linear(hidden_dim, out_channels)

    def forward(self, x: torch.Tensor, embedding: torch.Tensor = None) -> torch.Tensor:
        """
        Args:
            x: Input image [B, C, H, W]
            embedding: Style/Metadata embedding [B, embedding_dim]
                       If None, uses a default zero embedding.

        forward method for HypernetworkGenerator.

        Executes PyTorch tensor operations.

        Args:
            x (torch.Tensor, shape (B, C, H, W) or (B, C, D, H, W)): Expected input tensor.
            embedding (torch.Tensor, shape (B, C, H, W) or (B, C, D, H, W)): Expected input tensor.

        Returns:
            torch.Tensor: Output tensor.

        Hardware/Device Context:
            Supports Mixed Precision (AMP) and CUDA streams if configured in DataStagingService."""
        B = x.shape[0]
        if embedding is None:
            embedding = torch.zeros((B, self.embedding_dim), device=x.device)

        # Generate weights
        features = self.hyper_net(embedding)

        w1 = self.w1_head(features).view(B, self.target_hidden, self.in_channels, 3, 3)
        b1 = self.b1_head(features).view(B, self.target_hidden)

        w2 = self.w2_head(features).view(B, self.out_channels, self.target_hidden, 3, 3)
        b2 = self.b2_head(features).view(B, self.out_channels)

        # Apply weights using batched grouped convolution for efficiency
        # Instead of looping over batch, we reshape to use groups=B
        # This provides O(1) batch dimension complexity vs O(B) loop

        # Reshape for grouped convolution: combine batch and channel dims
        # x: [B, C_in, H, W] -> [1, B*C_in, H, W]
        _, C_in, H, W = x.shape
        x_grouped = x.view(1, B * C_in, H, W)

        # w1: [B, C_hidden, C_in, 3, 3] -> [B*C_hidden, C_in, 3, 3] (groups=B)
        w1_grouped = w1.view(B * self.target_hidden, self.in_channels, 3, 3)
        b1_grouped = b1.view(B * self.target_hidden)

        # Layer 1: grouped conv with groups=B
        h = F.conv2d(x_grouped, w1_grouped, bias=b1_grouped, padding=1, groups=B)
        h = F.relu(h)
        # h: [1, B*C_hidden, H, W]

        # w2: [B, C_out, C_hidden, 3, 3] -> [B*C_out, C_hidden, 3, 3]
        w2_grouped = w2.view(B * self.out_channels, self.target_hidden, 3, 3)
        b2_grouped = b2.view(B * self.out_channels)

        # Layer 2: grouped conv with groups=B
        y = F.conv2d(h, w2_grouped, bias=b2_grouped, padding=1, groups=B)
        # y: [1, B*C_out, H, W]

        # Reshape back to [B, C_out, H, W]
        return y.view(B, self.out_channels, H, W)

    def get_parameter_count(self) -> int:
        """get_parameter_count.

        Returns:
            int: Description.
        """
        return sum(p.numel() for p in self.parameters())

    def get_output_shape(self, input_shape: tuple[int, ...]) -> tuple[int, ...]:
        """get_output_shape.

        Args:
            input_shape (tuple[int, ...]): Description.
        Returns:
            tuple[int, ...]: Description.
        """
        return input_shape

    def generate(self, z: torch.Tensor, **kwargs) -> torch.Tensor:
        """Generate samples - for Hypernetwork, z is the input state."""
        return self.forward(z)

    @property
    def name(self) -> str:
        """name.

        Returns:
            str: Description.
        """
        return "hypernetwork_generator"
