"""B₀-Conditioned HyperNetwork for Continuous Field Interpolation.

Generates the convolution weights of a reconstruction U-Net dynamically
based on a continuous scalar B₀ field strength input. This enables
smooth interpolation between field strengths (64mT → 0.55T → 1.5T → 3T)
rather than training separate discrete models.

Mathematical Foundation:
    θ_G = H_φ(B₀)
    ŷ_{B₀} = G_{H_φ(B₀)}(x_ulf)

The HyperNetwork learns a continuous manifold over network weight space
parameterized by the Larmor frequency, forcing the latent space to
organize according to the physics of magnetic resonance.

References:
    - Ha, D. et al. (2016). "HyperNetworks." ICLR.
    - Littwin, E. & Wolf, L. (2019). "Deep Meta Functionals." ICLR.
"""

from __future__ import annotations

import logging
import math

import torch
import torch.nn as nn

logger = logging.getLogger(__name__)


class B0HyperNetwork(nn.Module):
    """HyperNetwork that generates conv weights conditioned on B₀ field strength.

    Takes a scalar B₀ (in Tesla) and produces weight tensors for a target
    network. Supports chunked weight generation for memory efficiency.

    Args:
        b0_embed_dim: Dimension for B₀ positional embedding.
        hidden_dim: Hidden layer dimension.
        num_layers: Number of MLP layers.
        target_param_count: Total number of parameters to generate.
        chunk_size: Generate weights in chunks of this size for memory.
        b0_range: (min, max) expected B₀ range for normalization.
    """

    def __init__(
        self,
        b0_embed_dim: int = 64,
        hidden_dim: int = 512,
        num_layers: int = 3,
        target_param_count: int = 100000,
        chunk_size: int = 50000,
        b0_range: tuple[float, float] = (0.01, 7.0),
    ) -> None:
        super().__init__()
        self.target_param_count = target_param_count
        self.chunk_size = chunk_size
        self.b0_min, self.b0_max = b0_range
        self.b0_embed_dim = b0_embed_dim

        # Sinusoidal positional embedding for B₀ (captures Larmor frequency)
        self.register_buffer(
            "freq_bands",
            torch.exp(torch.linspace(0, math.log(1000), b0_embed_dim // 2)),
        )

        # Build MLP
        layers: list[nn.Module] = []
        in_dim = b0_embed_dim
        for i in range(num_layers - 1):
            layers.extend(
                [
                    nn.Linear(in_dim, hidden_dim),
                    nn.LayerNorm(hidden_dim),
                    nn.GELU(),
                ]
            )
            in_dim = hidden_dim

        self.backbone = nn.Sequential(*layers)

        # Chunked output heads
        n_chunks = max(1, (target_param_count + chunk_size - 1) // chunk_size)
        self.heads = nn.ModuleList()
        remaining = target_param_count
        for _ in range(n_chunks):
            out_size = min(chunk_size, remaining)
            self.heads.append(nn.Linear(hidden_dim, out_size))
            remaining -= out_size

    def _embed_b0(self, b0: torch.Tensor) -> torch.Tensor:
        """Sinusoidal embedding of B₀ value.

        Args:
            b0: Field strength tensor [B] or scalar.

        Returns:
            Embedding [B, b0_embed_dim].
        """
        if b0.ndim == 0:
            b0 = b0.unsqueeze(0)

        # Normalize to [0, 1]
        b0_norm = (b0 - self.b0_min) / (self.b0_max - self.b0_min + 1e-8)
        b0_norm = b0_norm.unsqueeze(-1)  # [B, 1]

        # Sinusoidal encoding (captures Larmor frequency harmonics)
        phases = b0_norm * self.freq_bands.unsqueeze(0)  # [B, D/2]
        return torch.cat([torch.sin(phases), torch.cos(phases)], dim=-1)  # [B, D]

    def forward(self, b0: torch.Tensor) -> torch.Tensor:
        """Generate target network weights for given B₀.

        Args:
            b0: Field strength in Tesla [B] or scalar.

        Returns:
            Flat weight vector [B, target_param_count].

        forward method for B0HyperNetwork.

        Executes PyTorch tensor operations.

        Args:
            b0 (torch.Tensor, shape (B, C, H, W) or (B, C, D, H, W)): Expected input tensor.

        Returns:
            torch.Tensor: Output tensor.

        Hardware/Device Context:
            Supports Mixed Precision (AMP) and CUDA streams if configured in DataStagingService."""
        emb = self._embed_b0(b0)  # [B, embed_dim]
        h = self.backbone(emb)  # [B, hidden_dim]

        # Generate weights in chunks
        chunks = [head(h) for head in self.heads]
        return torch.cat(chunks, dim=-1)  # [B, target_param_count]


class B0ConditionedGenerator(nn.Module):
    """Generator with weights dynamically produced by a B₀ HyperNetwork.

    Wraps a base generator architecture and replaces its conv weights
    with those generated by the HyperNetwork at each forward pass.

    Args:
        base_generator: The template generator (weights will be overwritten).
        hyper_network: B0HyperNetwork that produces weights.
    """

    def __init__(
        self,
        base_generator: nn.Module,
        hyper_network: B0HyperNetwork,
    ) -> None:
        super().__init__()
        self.base_generator = base_generator
        self.hyper_network = hyper_network

        # Cache parameter shapes for unpacking
        self._param_shapes: list[tuple[str, torch.Size]] = []
        total = 0
        for name, param in base_generator.named_parameters():
            self._param_shapes.append((name, param.shape))
            total += param.numel()

        if total != hyper_network.target_param_count:
            logger.warning(
                "HyperNetwork target_param_count=%d != generator params=%d. "
                "Only the first %d parameters will be overwritten.",
                hyper_network.target_param_count,
                total,
                min(total, hyper_network.target_param_count),
            )

    def _inject_weights(self, flat_weights: torch.Tensor) -> None:
        """Unpack flat weight vector into the base generator's parameters."""
        offset = 0
        state = dict(self.base_generator.named_parameters())
        for name, shape in self._param_shapes:
            numel = shape.numel()
            if offset + numel > flat_weights.shape[-1]:
                break
            chunk = flat_weights[0, offset : offset + numel].reshape(shape)
            state[name].data.copy_(chunk)
            offset += numel

    def forward(
        self,
        x: torch.Tensor,
        b0: torch.Tensor | float = 3.0,
    ) -> torch.Tensor:
        """Forward pass with B₀-conditioned weights.

        Args:
            x: Input image [B, C, H, W].
            b0: Target field strength in Tesla. Scalar or [B].

        Returns:
            Generated output at the specified field strength.

        forward method for B0ConditionedGenerator.

        Executes PyTorch tensor operations.

        Args:
            x (torch.Tensor, shape (B, C, H, W) or (B, C, D, H, W)): Expected input tensor.
            b0 (torch.Tensor, shape (B, C, H, W) or (B, C, D, H, W)): Expected input tensor.

        Returns:
            torch.Tensor: Output tensor.

        Hardware/Device Context:
            Supports Mixed Precision (AMP) and CUDA streams if configured in DataStagingService."""
        if isinstance(b0, (int, float)):
            b0 = torch.tensor([b0], device=x.device, dtype=x.dtype)

        # Generate weights
        weights = self.hyper_network(b0)

        # Inject into generator
        self._inject_weights(weights)

        # Forward through the weight-injected generator
        return self.base_generator(x)


__all__ = [
    "B0ConditionedGenerator",
    "B0HyperNetwork",
]
