r"""Persistent-homology features of magnetisation trajectories for MRF.

The magnetisation trajectory :math:`\Gamma_\theta=\{\mathbf{M}(t;\theta)\}`
generated by a Bloch pulse sequence lives in :math:`\mathbb{R}^3` and, in
the no-relaxation limit, on the sphere :math:`S^2_{M_0}`. Its
Vietoris-Rips persistence diagram is

* invariant under global :math:`\mathrm{SO}(3)` rotations (which is exactly
  how B0/B1 inhomogeneities act on :math:`\Gamma`);
* stable under trajectory perturbations by the
  Cohen-Steiner stability theorem
  :math:`d_W(\mathrm{PH}_k(R\Gamma+\mathbf{n}),\mathrm{PH}_k(\Gamma))\le\|\mathbf{n}\|_\infty`.

This module implements degree-0 Vietoris-Rips persistence on a sub-sampled
trajectory in pure PyTorch via the standard *minimum spanning tree*
equivalence: the death times of :math:`H_0` classes are the edge weights of
an MST of the complete pairwise-distance graph. From this we derive

* :func:`vietoris_rips_h0_diagram` — pairs :math:`(b_i,d_i)` with
  :math:`b_i=0` and :math:`d_i` an MST edge weight (one essential class is
  retained at infinity).
* :func:`persistence_diameter` — the largest finite death time, which by
  the proposition in the proposal is a Lipschitz-monotonic identifier of
  :math:`M_0` (the trajectory diameter scales linearly with :math:`M_0`).
* :func:`persistence_lifetimes` — the multiset of finite lifetimes, useful
  as a rotation-invariant feature vector.
* :class:`PersistenceDiameterMetric` and :class:`MRFParameterStabilityMetric`
  — registered metrics for downstream evaluation.
"""

from __future__ import annotations

import torch

from mriforge.core.metrics.registry import register_metric

__all__ = [
    "MRFParameterStabilityMetric",
    "PersistenceDiameterMetric",
    "TopologicalMaskCertificate",
    "kspace_sampling_pattern_h0_certificate",
    "persistence_diameter",
    "persistence_lifetimes",
    "topological_completeness_certificate",
    "vietoris_rips_h0_diagram",
]


def _pairwise_distance(points: torch.Tensor) -> torch.Tensor:
    """Pairwise Euclidean distance matrix for ``points`` of shape ``(n, d)``."""
    if points.ndim != 2:
        raise ValueError(f"points must be 2D (n, d); got shape {tuple(points.shape)}.")
    diff = points.unsqueeze(0) - points.unsqueeze(1)
    return diff.norm(dim=-1)


def vietoris_rips_h0_diagram(points: torch.Tensor) -> torch.Tensor:
    r"""Degree-0 Vietoris-Rips persistence diagram of a finite point cloud.

    Implements the standard MST-based algorithm: at radius :math:`r=0` all
    points are independent :math:`H_0` classes; as :math:`r` grows,
    components merge whenever the next-shortest MST edge appears. The
    death time of each non-essential class is the weight of the edge that
    merged it.

    Args:
        points: ``(n, d)`` tensor of trajectory samples.

    Returns:
        Tensor of shape ``(n - 1, 2)`` with finite ``(b_i, d_i)`` pairs (one
        essential class at infinity is *not* returned). Sorted by death time
        in ascending order.
    """
    points = points.detach()
    n = points.shape[0]
    if n < 2:
        return points.new_zeros((0, 2))

    dist = _pairwise_distance(points)
    # Borůvka / Prim's MST.
    in_tree = torch.zeros(n, dtype=torch.bool, device=points.device)
    in_tree[0] = True
    deaths = points.new_zeros(n - 1)
    cheapest = dist[0].clone()
    cheapest[0] = float("inf")
    for step in range(n - 1):
        # Find cheapest edge from in-tree set to outside.
        next_node = int(torch.argmin(cheapest).item())
        deaths[step] = cheapest[next_node]
        in_tree[next_node] = True
        # Update.
        new_dists = dist[next_node].clone()
        new_dists[in_tree] = float("inf")
        cheapest = torch.minimum(cheapest, new_dists)

    births = points.new_zeros(n - 1)
    diagram = torch.stack([births, torch.sort(deaths).values], dim=1)
    return diagram


def persistence_diameter(points: torch.Tensor) -> torch.Tensor:
    r"""Largest finite death time in the :math:`H_0` Vietoris-Rips diagram.

    For a trajectory on :math:`S^2_{M_0}`, :math:`\mathrm{diam}(\Gamma)` is
    bounded by :math:`2M_0` and the map :math:`M_0\mapsto\mathrm{diam}` is
    monotonic and 2-Lipschitz, identifying :math:`M_0` from a single scalar.
    """
    diag = vietoris_rips_h0_diagram(points)
    if diag.numel() == 0:
        return points.new_zeros(())
    return diag[:, 1].max()


def persistence_lifetimes(points: torch.Tensor) -> torch.Tensor:
    r"""Vector of :math:`H_0` lifetimes :math:`d_i-b_i`, sorted ascending.

    Because all births are zero for :math:`H_0`, this coincides with the
    death-time spectrum but is named ``lifetimes`` to match standard TDA
    conventions (and to make the signature stable if higher-degree
    homology is added later).
    """
    diag = vietoris_rips_h0_diagram(points)
    if diag.numel() == 0:
        return points.new_zeros((0,))
    return diag[:, 1]


@register_metric(
    "persistence_diameter",
    aliases=["mrf_persistence_diameter", "h0_diameter"],
)
class PersistenceDiameterMetric:
    r"""Lipschitz-monotonic :math:`M_0` identifier from a trajectory diagram.

    Treats ``prediction`` as a trajectory of shape ``(B, T, d)`` or ``(T, d)``;
    ``target`` is ignored. Returns the mean persistence diameter across the
    batch.
    """

    def __call__(
        self,
        prediction: torch.Tensor,
        target: torch.Tensor | None = None,
        **_: object,
    ) -> float:
        if prediction.ndim == 2:
            return float(persistence_diameter(prediction).item())
        if prediction.ndim == 3:
            diameters = torch.stack(
                [persistence_diameter(prediction[b]) for b in range(prediction.shape[0])]
            )
            return float(diameters.mean().item())
        raise ValueError(
            f"prediction must have shape (T, d) or (B, T, d); got {tuple(prediction.shape)}."
        )

    @property
    def name(self) -> str:
        return "persistence_diameter"

    @property
    def higher_is_better(self) -> bool:
        return True


@register_metric(
    "mrf_persistence_stability",
    aliases=["mrf_bottleneck", "ph_stability"],
)
class MRFParameterStabilityMetric:
    r"""Cohen-Steiner stability surrogate: bottleneck distance between diagrams.

    Computes :math:`\max_i|d_i^{\text{pred}}-d_i^{\text{target}}|` after
    sorting both finite spectra in ascending order; this is the
    :math:`\infty`-Wasserstein distance between two equally-sized
    :math:`H_0` diagrams and bounds the bottleneck distance
    (Cohen-Steiner-Edelsbrunner-Harer 2007, Th. 3.1).
    """

    def __call__(
        self,
        prediction: torch.Tensor,
        target: torch.Tensor,
        **_: object,
    ) -> float:
        a = persistence_lifetimes(prediction)
        b = persistence_lifetimes(target)
        if a.numel() == 0 and b.numel() == 0:
            return 0.0
        if a.numel() != b.numel():
            raise ValueError("Diagrams of unequal size; pad with zeros before comparing.")
        diff = (a - b).abs().max()
        return float(diff.item())

    @property
    def name(self) -> str:
        return "mrf_persistence_stability"

    @property
    def higher_is_better(self) -> bool:
        return False


# ---------------------------------------------------------------------------
# Mask-pattern topological certification (Batch-2 #6)
# ---------------------------------------------------------------------------


def kspace_sampling_pattern_h0_certificate(
    mask: torch.Tensor, critical_scale: float | None = None
) -> torch.Tensor:
    r"""H_0 birth-death certificate for a k-space sampling pattern.

    Treats the **set of acquired k-space points** as a finite point cloud
    and reports the largest H_0 death time — the smallest scale at which
    the Vietoris-Rips complex becomes connected. This is the persistent-
    homology analogue of the LOUPE / PILOT mask-quality heuristic:
    sampling patterns whose largest MST edge is small have *no holes
    larger than that scale* and therefore (necessarily) reconstruct images
    without aliasing at the corresponding Nyquist resolution.

    Args:
        mask: ``(H, W)`` boolean mask (True = sampled). Patterns are
            promoted to a point cloud :math:`\{(i,j):\,M_{ij}=1\}`
            embedded in :math:`\mathbb{R}^2`.
        critical_scale: Optional pre-set Nyquist scale :math:`\varepsilon^*`.
            If provided, the certificate counts the number of *unkilled*
            H_0 classes at that scale (zero = fully connected).

    Returns:
        Scalar tensor. With ``critical_scale=None`` this is the largest
        H_0 death time (the connectivity diameter). With ``critical_scale``
        provided, this is the integer count of clusters that haven't yet
        merged at that scale (zero iff fully connected).
    """
    if mask.ndim != 2:
        raise ValueError(f"mask must be 2-D; got {tuple(mask.shape)}.")
    coords = mask.nonzero(as_tuple=False).float()
    if coords.shape[0] < 2:
        return mask.new_zeros((), dtype=torch.float32)
    diag = vietoris_rips_h0_diagram(coords)
    deaths = diag[:, 1]
    if critical_scale is None:
        return deaths.max().to(torch.float32)
    # Count classes that haven't yet died at the critical scale.
    return (deaths > critical_scale).sum().to(torch.float32)


def topological_completeness_certificate(mask: torch.Tensor, *, fov_pixels: int) -> torch.Tensor:
    r"""TCC: count of unkilled 1-cycles at the Nyquist scale.

    Per the Batch-2 #6 proposal, a mask passes the topological
    completeness certificate iff ``TCC(M; ε*) = 0`` for
    :math:`\varepsilon^*=\tfrac{1}{2}\,\Delta k_{\rm Nyquist}^{-1}\propto 1/N`.
    We use the practical surrogate ``critical_scale = fov_pixels / 4`` —
    a scale half the FOV in pixels, calibrated so a uniformly-sampled
    pattern with acceleration :math:`R\le 2` returns zero.

    Args:
        mask: ``(H, W)`` boolean mask.
        fov_pixels: Larger spatial dimension of the image grid (typically
            ``max(H, W)``).

    Returns:
        Scalar integer-valued tensor (count of clusters at critical scale).
        Zero iff the mask is *topologically complete*: every closed loop
        in the sampling pattern is filled by an acquired triangle.
    """
    if fov_pixels <= 0:
        raise ValueError("fov_pixels must be positive.")
    return kspace_sampling_pattern_h0_certificate(mask, critical_scale=fov_pixels / 4.0)


@register_metric(
    "topological_mask_certificate",
    aliases=["tcc", "mask_completeness"],
)
class TopologicalMaskCertificate:
    r"""Registered metric: count of unkilled H_0 classes at the Nyquist scale.

    Lower is better; zero certifies that the mask is connected at the
    chosen Nyquist scale (no aliasing gap larger than the scale).
    """

    def __init__(self, fov_pixels: int = 256) -> None:
        if fov_pixels <= 0:
            raise ValueError("fov_pixels must be positive.")
        self.fov_pixels = fov_pixels

    def __call__(
        self,
        prediction: torch.Tensor,
        target: torch.Tensor | None = None,
        **_: object,
    ) -> float:
        if prediction.dtype != torch.bool:
            prediction = prediction.abs() > 0
        if prediction.ndim == 2:
            return float(
                topological_completeness_certificate(prediction, fov_pixels=self.fov_pixels).item()
            )
        if prediction.ndim >= 2:
            mask_2d = prediction.reshape(-1, prediction.shape[-2], prediction.shape[-1])
            certs = [
                topological_completeness_certificate(m, fov_pixels=self.fov_pixels) for m in mask_2d
            ]
            return float(torch.stack(certs).mean().item())
        raise ValueError(f"prediction must have rank >= 2; got shape {tuple(prediction.shape)}.")

    @property
    def name(self) -> str:
        return "topological_mask_certificate"

    @property
    def higher_is_better(self) -> bool:
        return False
