r"""Unit tests for the acquisition-flow Lie-derivative loss (AFE).

Targets ``spectramr.models.losses.acq_flow_lie_loss``.

AFE makes a representation equivariant to the *contrast flow generated by the
acquisition parameters themselves*. The signal equation generates a vector field
:math:`\mathbf v_{\boldsymbol\varphi}=\partial_{\boldsymbol\varphi}\mathcal
F^{\mathrm{Bloch}}`, and the penalty drives the feature map's Lie derivative
along it to zero (invariant case). The decisive consistency check: where contrast
is insensitive to a parameter (TR >> T1, so :math:`\partial_{\mathrm{TR}}\mathcal
F\to0`) the generator vanishes and the penalty imposes no constraint.
"""

from __future__ import annotations

import pytest
import torch

pytestmark = pytest.mark.unit

_ACQ = {"TR": 1500.0, "TE": 80.0, "TI": 0.0}


def _params() -> torch.Tensor:
    rho = torch.tensor([[[[1.0, 0.8], [0.6, 0.9]]]])
    t1 = torch.tensor([[[[800.0, 1200.0], [600.0, 1000.0]]]])
    t2 = torch.tensor([[[[80.0, 120.0], [60.0, 100.0]]]])
    return torch.cat([rho, t1, t2], dim=1)


def test_generator_vanishes_when_tr_much_greater_than_t1() -> None:
    """Consistency: the flow generator -> 0 where the contrast is TR-insensitive."""
    from spectramr.models.losses.acq_flow_lie_loss import acquisition_flow_generator

    params = _params()
    v_sat = acquisition_flow_generator(
        params, {"TR": 1.0e7, "TE": 80.0}, wrt="TR", contrast_type="spin_echo"
    )
    v_active = acquisition_flow_generator(
        params, {"TR": 500.0, "TE": 80.0}, wrt="TR", contrast_type="spin_echo"
    )
    assert v_sat.abs().max() < 1e-4
    assert v_active.abs().max() > v_sat.abs().max()


def test_generator_nonzero_for_te_sensitive_contrast() -> None:
    from spectramr.models.losses.acq_flow_lie_loss import acquisition_flow_generator

    params = _params()
    v_te = acquisition_flow_generator(
        params, _ACQ, wrt="TE", contrast_type="spin_echo"
    )
    assert v_te.shape == params[:, 0:1].shape
    assert v_te.abs().max() > 1e-4


def test_loss_zero_when_features_invariant() -> None:
    from spectramr.models.losses.acq_flow_lie_loss import AcquisitionFlowLieLoss

    feat = torch.randn(2, 4, 8, 8)
    loss = AcquisitionFlowLieLoss()(prediction=feat, target=feat.clone())
    assert float(loss) == pytest.approx(0.0, abs=1e-7)


def test_loss_positive_when_features_drift_along_flow() -> None:
    from spectramr.models.losses.acq_flow_lie_loss import AcquisitionFlowLieLoss

    feat = torch.randn(2, 4, 8, 8)
    flowed = feat + 0.3 * torch.randn_like(feat)
    loss = AcquisitionFlowLieLoss()(prediction=feat, target=flowed)
    assert float(loss) > 1e-3


def test_loss_is_registered() -> None:
    from spectramr.models.losses import create_loss
    from spectramr.models.losses.acq_flow_lie_loss import AcquisitionFlowLieLoss

    assert isinstance(create_loss("acq_flow_lie"), AcquisitionFlowLieLoss)
