r"""Primary-ideal membership loss for quantitative parameter maps.

Closes the ``primary_ideal`` strategy façade. The advertised mathematics is
primary decomposition (Lasker--Noether): a variety is a finite union of
irreducible components, and the vanishing ideal of a union is generated by
the **product** of the component generators. This loss penalizes the
prediction's vanishing-ideal residual against tissue-component varieties
derived from the target, pushing each predicted voxel's :math:`(M_0,T_1,T_2)`
onto the algebraic union of tissue-class shells.

See :mod:`mriforge.infrastructure.physics.primary_ideal` for the algebraic
primitives (this is an honest *surrogate* of primary decomposition — the
union-of-varieties product structure — not a full Gröbner-basis routine).
"""

from __future__ import annotations

import torch
import torch.nn as nn

from mriforge.infrastructure.physics.primary_ideal import vanishing_ideal_residual
from mriforge.models.losses.registry import register_loss


@register_loss(
    name="primary_ideal_membership",
    aliases=["primary_decomposition", "vanishing_ideal"],
    domain="image",
)
class PrimaryIdealMembershipLoss(nn.Module):
    r"""Penalize departure from the union of tissue-component varieties.

    The target's voxels are clustered (detached) into ``n_components``
    quadratic component centres; the radius of each shell is the RMS spread
    of its members. The loss is the mean vanishing-ideal residual
    :math:`|\prod_k g_k(\theta_{\text{pred}})|` (log-domain, normalised),
    minimal when predicted voxels sit on a component shell.

    Args:
        n_components: Number of primary components ``K`` (tissue classes).
        reduction: ``"mean"`` or ``"sum"``.
        eps: Numerical floor.
    """

    def __init__(
        self,
        n_components: int = 3,
        reduction: str = "mean",
        eps: float = 1e-6,
    ) -> None:
        super().__init__()
        if n_components < 1:
            raise ValueError("n_components must be >= 1")
        if reduction not in ("mean", "sum"):
            raise ValueError(f"reduction must be mean/sum, got {reduction!r}")
        self.n_components = n_components
        self.reduction = reduction
        self.eps = eps

    @staticmethod
    def _cluster(points: torch.Tensor, k: int, iters: int = 5) -> tuple[torch.Tensor, torch.Tensor]:
        """Lloyd's algorithm (detached) → (centers [k,d], radii [k])."""
        n = points.shape[0]
        # Deterministic init: k quantile points along the first coordinate order.
        order = torch.argsort(points[:, 0])
        idx = torch.linspace(0, n - 1, k, device=points.device).round().long()
        centers = points[order[idx]].clone()
        for _ in range(iters):
            d2 = torch.cdist(points, centers)  # [n, k]
            assign = d2.argmin(dim=1)
            new = []
            for c in range(k):
                members = points[assign == c]
                new.append(members.mean(0) if members.numel() else centers[c])
            centers = torch.stack(new, dim=0)
        d2 = torch.cdist(points, centers)
        assign = d2.argmin(dim=1)
        radii = []
        for c in range(k):
            members = points[assign == c]
            if members.numel():
                radii.append(((members - centers[c]).pow(2).sum(-1).mean().clamp_min(1e-8)).sqrt())
            else:
                radii.append(torch.tensor(1.0, device=points.device))
        return centers, torch.stack(radii)

    def forward(
        self,
        prediction: torch.Tensor,
        target: torch.Tensor,
        **kwargs: object,
    ) -> torch.Tensor:
        if prediction.shape != target.shape:
            raise ValueError(
                f"shape mismatch: pred {tuple(prediction.shape)} vs target {tuple(target.shape)}"
            )
        if prediction.ndim != 4 or prediction.shape[1] < 1:
            raise ValueError(
                f"expected parameter maps [B, C>=1, H, W], got {tuple(prediction.shape)}"
            )
        d = prediction.shape[1]
        pred_pts = prediction.permute(0, 2, 3, 1).reshape(-1, d)
        tgt_pts = target.permute(0, 2, 3, 1).reshape(-1, d).detach()

        k = min(self.n_components, tgt_pts.shape[0])
        centers, radii = self._cluster(tgt_pts, k)

        residual = vanishing_ideal_residual(pred_pts, centers, radii)
        # Normalise by the component scale so the magnitude is comparable
        # across parameter ranges; log1p keeps the high-degree product tame.
        scale = radii.pow(2).prod().clamp_min(self.eps)
        residual = torch.log1p(residual / scale)
        return residual.mean() if self.reduction == "mean" else residual.sum()


__all__ = ["PrimaryIdealMembershipLoss"]
