"""Differentiable cubical persistent homology with Wasserstein-2 distance.

Computes the persistence diagrams of the sublevel-set filtration of
prediction and target volumes (cubical complex on the foreground
mask), then takes the Wasserstein-2 distance between them as the
loss.

Stability guarantee (Cohen-Steiner, Edelsbrunner, Harer 2007):

.. math::

    W_2(\\mathrm{Dgm}(\\hat I), \\mathrm{Dgm}(I)) \\le \\| \\hat I - I \\|_2

so this term is well-conditioned with respect to the L2 reconstruction
loss.

Backend: :mod:`gudhi` for the cubical PH computation, :mod:`POT` for
the Wasserstein-2 distance. Both are pulled in via the
``[topology]`` extra in :file:`pyproject.toml`. Module import is
unconditional so the registry registration succeeds; an
``ImportError`` is raised at *instantiation* time with a useful
message if either dep is missing.

Distinct from
:class:`spectramr.models.losses.topological_loss.PersistentHomologyLoss`
which approximates Betti-0 only via differentiable Euler
characteristic on super-level sets — see plan §10 risk register
for the comparison.

Differentiable persistence: gradients of the loss with respect to
the prediction tensor are obtained by routing the W2-matched birth
/ death values back to the critical cells that produced them. Each
persistence pair :math:`(b, d)` is generated by a specific pair of
top-dimensional cells, located exactly via gudhi's
``cofaces_of_persistence_pairs`` (not by value matching, which is
ambiguous under ties — e.g. a large flat / masked background), so
the chain rule is a two-voxel scatter — see Carrière et al. (2021)
"Optimizing persistent homology based functions" (ICML).

The implementation computes PH on the *detached* numpy view, matches
the resulting diagrams under the L∞-ground-metric W_p distance
(genuine matches pull pred's ``(birth, death)`` toward the target's;
diagonal matches push a hallucinated pred feature's persistence to
zero), and re-forms the loss as a sum of per-pair tensor terms that
are linear-in-pred and therefore autograd-traceable.
"""

from __future__ import annotations

import platform
from typing import Any

import torch
import torch.nn as nn

from spectramr.models.losses.registry import register_loss

try:
    import gudhi as _gudhi  # type: ignore[import-untyped]
except ImportError:  # pragma: no cover - environment dependent
    _gudhi = None

try:
    import ot as _ot  # type: ignore[import-untyped]
except ImportError:  # pragma: no cover - environment dependent
    _ot = None


def _install_hint() -> str:
    """Name the package(s) actually missing, and say when the extra cannot supply them.

    Reporting the union ("requires [topology]") infers absence rather than
    stating it (NN18): the two imports are guarded separately, so exactly which
    one is gone is known and must be said. On Linux aarch64 it is further known
    that the extra *cannot* help -- gudhi publishes no aarch64 wheel and no
    sdist -- so pointing there would send the user round a loop that always ends
    back here.
    """
    missing = [n for n, m in (("gudhi", _gudhi), ("POT (ot)", _ot)) if m is None]
    hint = f"CubicalPHWassersteinLoss requires {' and '.join(missing)} (the [topology] extra)."
    if _gudhi is None and (platform.system(), platform.machine()) == ("Linux", "aarch64"):
        return (
            f"{hint}\n"
            "gudhi ships no aarch64 wheel and no sdist, so [topology] cannot install it "
            "on this machine -- the cubical_ph_w2 loss is unavailable on linux/aarch64. "
            "Run these arms on x86_64."
        )
    return (
        f'{hint}\nInstall with:\n    pip install -e ".[topology]"\nor:\n    make install-topology'
    )


@register_loss(
    name="cubical_ph_w2",
    aliases=["CubicalPHWasserstein", "ph_w2", "persistent_homology_w2"],
)
class CubicalPHWassersteinLoss(nn.Module):
    """Cubical PH + Wasserstein-2 between prediction and target volumes.

    Args:
        homology_dims: which homology dimensions to track. Cubical PH
            in 3D supports 0, 1, 2 (components, loops, voids).
        wasserstein_p: Wasserstein order. The plan calls for p=2
            (Cohen-Steiner stability theorem holds for any p >= 1).
        stratify_subvolumes: number of equal-volume sub-blocks the
            input is split into for PH computation. Reduces the
            cubical-complex size from N^3 to (N/k)^3 per call.

    Returns a scalar loss in the standard ``(pred, target)`` shape
    contract; an optional ``mask`` kwarg is honored by zeroing out
    background voxels before the filtration.
    """

    def __init__(
        self,
        homology_dims: tuple[int, ...] | list[int] = (0, 1),
        wasserstein_p: int = 2,
        stratify_subvolumes: int = 1,
    ) -> None:
        super().__init__()
        if _gudhi is None or _ot is None:
            raise ImportError(_install_hint())
        if wasserstein_p < 1:
            raise ValueError(f"wasserstein_p must be >= 1, got {wasserstein_p}")
        if stratify_subvolumes < 1:
            raise ValueError(f"stratify_subvolumes must be >= 1, got {stratify_subvolumes}")
        self.homology_dims = tuple(homology_dims)
        self.wasserstein_p = wasserstein_p
        self.stratify_subvolumes = stratify_subvolumes

    def forward(
        self,
        pred: torch.Tensor,
        target: torch.Tensor,
        mask: torch.Tensor | None = None,
        **kwargs: Any,
    ) -> torch.Tensor:
        """Compute the PH-W2 loss.

        Args:
            pred: predicted volume of shape ``(B, C, ...)`` (any number
                of spatial dimensions; cubical PH treats each
                ``(B, C)`` slice as a separate filtration).
            target: ground-truth volume, same shape as ``pred``.
            mask: optional foreground mask of the same shape; values
                outside the mask are pushed to ``+inf`` for the
                sublevel-set filtration so they enter only at the top
                of the filtration and contribute no finite features.

        Returns:
            Scalar loss tensor with the autograd graph attached
            through the birth-voxel scatter.
        """
        if pred.shape != target.shape:
            raise ValueError(
                f"pred and target must have the same shape, got "
                f"{tuple(pred.shape)} vs {tuple(target.shape)}"
            )
        if mask is not None and mask.shape != pred.shape:
            raise ValueError(
                "mask must have the same shape as pred when provided "
                f"(pred={tuple(pred.shape)}, mask={tuple(mask.shape)})"
            )
        if pred.ndim < 3:
            raise ValueError(
                f"pred must have at least 3 dimensions (B, C, *spatial), got {pred.ndim}"
            )

        device = pred.device
        dtype = pred.dtype
        loss = torch.zeros((), device=device, dtype=dtype)
        n_pairs = 0

        # Iterate over (batch, channel) slices — cubical PH is computed
        # independently per slice. The cost is O(B * C * |spatial|).
        for b in range(pred.shape[0]):
            for c in range(pred.shape[1]):
                p_slice = pred[b, c]
                t_slice = target[b, c]
                if mask is not None:
                    m_slice = mask[b, c]
                    # Push background voxels above the largest finite
                    # value so they form no sublevel features.
                    p_slice = torch.where(
                        m_slice > 0, p_slice, torch.full_like(p_slice, float("inf"))
                    )
                    t_slice = torch.where(
                        m_slice > 0, t_slice, torch.full_like(t_slice, float("inf"))
                    )

                pair_loss = self._slice_loss(p_slice, t_slice)
                loss = loss + pair_loss
                n_pairs += 1

        return loss / max(n_pairs, 1)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _slice_loss(self, pred_slice: torch.Tensor, target_slice: torch.Tensor) -> torch.Tensor:
        """Compute the W2 loss for a single slice with autograd."""
        # Compute persistence diagrams on detached numpy views.
        pred_np = pred_slice.detach().cpu().numpy()
        target_np = target_slice.detach().cpu().numpy()

        pred_dgm, pred_birth_voxels, pred_death_voxels = self._persistence_with_voxels(pred_np)
        target_dgm, _, _ = self._persistence_with_voxels(target_np)

        if pred_dgm.size == 0:
            # No finite pred features to match or penalise (constant volume /
            # fully masked-out slice). Zero loss with zero gradient is correct.
            # NOTE: we do NOT early-return when only the *target* diagram is
            # empty — a topologically-trivial target with a hallucinating pred
            # must still be penalised (every pred feature matches the diagonal),
            # else the loss is blind to spurious topology (F2).
            return torch.zeros((), device=pred_slice.device, dtype=pred_slice.dtype)

        # POT expects (n, 2) float64 arrays for diagrams.
        assert _ot is not None  # narrowed by __init__ guard
        a = pred_dgm.astype("float64")
        b = target_dgm.astype("float64")

        # Wasserstein matching between diagrams. Use POT's optimal
        # transport on the diagram point cloud against itself + a
        # diagonal projection (standard PH-W2 trick).
        _cost, transport = _wasserstein_matching(a, b, p=self.wasserstein_p, ot_module=_ot)

        # Re-form the loss as a sum of per-pair tensor terms so that
        # autograd routes back through pred_slice via the birth AND
        # death voxels. Using the birth voxel for both diffs (the
        # previous "standard simplification" cited Carrière et al.
        # §3.2) double-counts the persistence: when pred == target the
        # match pairs each point with itself, target_death == pred_death,
        # but flat_pred[birth_voxel] == pred_birth, so the death term
        # contributes (pred_birth - pred_death)^p = persistence^p
        # instead of 0. Tracking the death voxel makes the loss vanish
        # at the optimum (the contract pinned by
        # tests/.../test_cubical_ph_w2_loss::test_identity_loss_is_near_zero).
        loss = torch.zeros((), device=pred_slice.device, dtype=pred_slice.dtype)
        flat_pred = pred_slice.reshape(-1)
        n_b = b.shape[0]
        for i, j in transport:
            birth_idx = pred_birth_voxels[i]
            death_idx = pred_death_voxels[i]
            if birth_idx < 0:
                # No source voxel to backprop into; gradient is zero anyway.
                continue
            if j < n_b:
                # Matched to a genuine target feature: pull pred's (birth, death)
                # toward the target's, under the L_infinity ground metric raised
                # to p -- max(|d_birth|, |d_death|)^p (matches the cost matrix in
                # _wasserstein_matching). Summing the coordinates would compute an
                # L_1 cost instead.
                target_birth = float(b[j, 0])
                target_death = float(b[j, 1])
                diff_b = flat_pred[birth_idx] - target_birth
                if death_idx >= 0:
                    diff_d = flat_pred[death_idx] - target_death
                else:
                    diff_d = torch.zeros((), device=flat_pred.device, dtype=flat_pred.dtype)
                pair_cost = torch.maximum(diff_b.abs(), diff_d.abs())
            else:
                # Matched to the DIAGONAL: pred has a feature the target lacks
                # (hallucinated topology). The L_infinity distance of a point
                # ``(b, d)`` to the diagonal is ``(d - b) / 2``; penalising it
                # here pushes birth up / death down, shrinking the spurious
                # feature's persistence to zero. Differentiable through both
                # pred voxels (F2 — previously this term was dropped, so the
                # loss was blind to hallucinated features).
                if death_idx < 0:
                    continue
                pair_cost = (flat_pred[death_idx] - flat_pred[birth_idx]).abs() / 2.0
            loss = loss + (pair_cost**self.wasserstein_p)

        # W_p distance is the p-th root of the matching cost. sqrt / pow(1/p)
        # have an INFINITE derivative at 0, so a perfect slice (loss == 0, i.e.
        # pred == target) would yield a NaN gradient (∞·0). Guard so the optimum
        # is an exact-zero loss with a finite (zero) gradient (F5); the identity
        # test previously never called .backward() so this was latent.
        positive = loss > 0
        safe = torch.where(positive, loss, torch.ones_like(loss))
        exponent = 0.5 if self.wasserstein_p == 2 else 1.0 / self.wasserstein_p
        root = safe.pow(exponent)
        return torch.where(positive, root, torch.zeros_like(loss))

    def _persistence_with_voxels(self, vol_np: Any) -> tuple[Any, list[int], list[int]]:
        """Compute persistence diagram + birth/death voxel indices for each pair.

        Returns:
            pairs: array of shape ``(n_pairs, 2)`` with (birth, death).
            birth_voxels: list of length ``n_pairs`` where each entry is
                the flat index in ``vol_np`` of the top-dimensional cell
                that *generates* the birth of the feature.
            death_voxels: same, for the cell generating the death.

        Cells are located via gudhi's ``cofaces_of_persistence_pairs``
        (the actual critical cells), not by ``argmin(|flat - value|)``:
        under value ties (a large flat or masked-out background) the
        value heuristic collapsed to the first/corner voxel, so the
        death gradient was scattered to the wrong voxel (F6). Tracking
        both cells is required so the W2 loss vanishes at ``pred ==
        target`` (see ``_slice_loss`` for the birth-only failure mode).
        """
        import numpy as np

        assert _gudhi is not None  # narrowed by __init__ guard
        cc = _gudhi.CubicalComplex(top_dimensional_cells=vol_np)
        cc.compute_persistence()
        flat = vol_np.reshape(-1)

        # cofaces_of_persistence_pairs() -> (regular, essential). ``regular`` is
        # grouped by homology dimension; each entry is an (n, 2) array of
        # (birth_cell, death_cell) flat indices into ``vol_np``. ``essential``
        # holds the infinite-persistence classes, which we drop for a finite
        # diagram W_p matching (the previous ``np.isfinite`` filter did the same).
        regular, _essential = cc.cofaces_of_persistence_pairs()

        pairs = []
        birth_voxels: list[int] = []
        death_voxels: list[int] = []
        for dim, arr in enumerate(regular):
            if dim not in self.homology_dims:
                continue
            for row in arr:
                birth_cell = int(row[0])
                death_cell = int(row[1])
                birth_val = float(flat[birth_cell])
                death_val = float(flat[death_cell])
                if not (np.isfinite(birth_val) and np.isfinite(death_val)):
                    # Pair touching a masked (+inf) region — no finite feature.
                    continue
                pairs.append((birth_val, death_val))
                birth_voxels.append(birth_cell)
                death_voxels.append(death_cell)

        return (
            np.asarray(pairs, dtype="float64").reshape(-1, 2),
            birth_voxels,
            death_voxels,
        )


def _wasserstein_matching(
    a: Any, b: Any, p: int, ot_module: Any
) -> tuple[float, list[tuple[int, int]]]:
    """Match two persistence diagrams under W_p; return (cost, pairs).

    Uses the augmented-with-diagonal trick: each diagram is padded
    with the orthogonal projection of the other diagram's points
    onto the diagonal, so the resulting matching always pairs
    every off-diagonal point with either an off-diagonal point in
    the other diagram or its own diagonal projection.
    """
    import numpy as np

    n_a, n_b = a.shape[0], b.shape[0]
    # Diagonal projections.
    a_diag = np.column_stack([(a.sum(axis=1) / 2.0)] * 2)
    b_diag = np.column_stack([(b.sum(axis=1) / 2.0)] * 2)

    # Stacked source / target sets (size n_a + n_b each).
    src = np.vstack([a, b_diag])
    tgt = np.vstack([b, a_diag])

    # Cost matrix: per-pair cost is the L_infinity ground metric raised to p,
    # i.e. max(|d_birth|, |d_death|)^p. This is the standard ground metric for
    # the persistence-diagram p-Wasserstein distance under which the
    # Cohen-Steiner stability theorem holds; the L_1 sum used previously
    # over-counts and breaks that bound. Since x -> x^p is monotone on x >= 0,
    # (|d|^p).max == (max|d|)^p.
    diff = src[:, None, :] - tgt[None, :, :]
    cost_matrix = (np.abs(diff) ** p).max(axis=2)

    # The diagonal<->diagonal block matches proj(b_l) against proj(a_k) — both
    # points lie ON the diagonal, so in the augmented-assignment reduction for
    # diagram W_p (Edelsbrunner-Harer; Kerber-Morozov-Nigmetov "Hera") its cost
    # must be identically 0. Leaving it at the true L_inf value adds a spurious,
    # matching-dependent penalty that mis-routes a genuine feature to the
    # diagonal (~9% of random diagrams) and flips the gradient direction (F2).
    cost_matrix[n_a:, n_b:] = 0.0

    # Uniform marginals -> exact OT via linear assignment.
    n = n_a + n_b
    weights = np.ones(n) / n
    transport_plan = ot_module.emd(weights, weights, cost_matrix)

    # Greedy decoding of the (sparse) transport plan into integer pairs. Every
    # off-diagonal pred point ``i`` is emitted, including those matched to the
    # diagonal (``j >= n_b``): the caller must penalise a pred feature the
    # target lacks by pushing it toward the diagonal (zero persistence), so
    # dropping those pairs here made the differentiable loss blind to
    # hallucinated topology (F2). ``j >= n_b`` flags a diagonal match.
    pairs: list[tuple[int, int]] = []
    for i in range(n_a):  # off-diagonal source points (pred diagram)
        j = int(np.argmax(transport_plan[i]))
        pairs.append((i, j))

    cost = float((cost_matrix * transport_plan).sum())
    return cost, pairs


__all__ = ["CubicalPHWassersteinLoss"]
